name: CI
on:
  push:
    branches:
      - main
      - development
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16"
      - run: yarn
      - run: yarn lint
  build:
    runs-on: ubuntu-latest
    needs: lint
    name: Build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16"
      - run: yarn
      - run: yarn build
  test:
    runs-on: ubuntu-latest
    needs: build
    name: Test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16"
      - run: yarn
      - run: yarn test
  lighthouse:
    runs-on: ubuntu-latest
    needs: build
    name: Lighthouse
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16"
      - run: yarn
      - run: yarn lighthouse
